# oscar.yaml
# Main run script that install all base software needed before 
# install the oscar.deb package.
#===================================================================
# Copyright Jake Swart 2017 released under the MIT License
#===================================================================
---

# To run: ansible-playbook oscarEmrAnsible/oscar.yaml --ask-become-pass -i "localhost," -c local
- hosts: web
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_user: root

  roles:
    - oscar

  tasks:

  #-----------------------------------------------------------------------
  # Oscar 15 Download, Install, Configure
  #-----------------------------------------------------------------------
  
  ## username is wrong here, set to pass??? consider change
  - name: Allow OSCAR to be able to login without using the plugin to pass linux {{MYSQL_USER}} credentials
    command: mysql -u{{MYSQL_USER}} -p{{MYSQL_PASSWORD}} -e "use mysql; update user set plugin='' where User='{{MYSQL_USER}}'; flush privileges;"
    changed_when: false

  - name: Ensure directory exists {{DOWN}}
    file: path={{DOWN}} state=directory

  - name: Prevent Redownload
    stat: path={{DOWN}}/{{OSCAR_PACKAGE}}
    register: stOscarDebFile

  - name: Download Oscar
    get_url: 
      dest: "{{DOWN}}/{{OSCAR_PACKAGE}}" 
      url: "http://sourceforge.net/projects/oscarmcmaster/files/Oscar%20Debian%2BUbuntu%20deb%20Package/{{OSCAR_PACKAGE}}"
      validate_certs: no
    when: stOscarDebFile.stat.exists is defined and not stOscarDebFile.stat.exists

  - name: Prevent ReInstall
    stat: path={{OSCAR_PROPERTIES}}
    register: stOscarPropertiesFile

  - block:

    - name: Temporarily Store oscar-emr/password in debconf database
      shell: echo "oscar-emr oscar-emr/password password {{MYSQL_PASSWORD}}" | debconf-set-selections

    - name: Temporarily Store oscar-emr/demo=false in debconf database
      shell: echo "oscar-emr oscar-emr/demo boolean false" | debconf-set-selections

    - name: Install Oscar Debian Package
      shell: DEBIAN_FRONTEND=noninteractive dpkg -i {{DOWN}}/{{OSCAR_PACKAGE}}

    - name: Cleanup oscar-emr/password in debconf database
      shell: echo "RESET oscar-emr/password" | debconf-communicate oscar-emr &>/dev/null
      ignore_errors: yes

    - name: Cleanup oscar-emr/demo in debconf database
      shell: echo "RESET oscar-emr/demo" | debconf-communicate oscar-emr &>/dev/null
      ignore_errors: yes

    when: stOscarPropertiesFile.stat.exists is defined and not stOscarPropertiesFile.stat.exists and OSCAR_DEB_VERSION|int >= 694

  - name: Install {{DOWN}}/{{OSCAR_PACKAGE}}
    debug: msg="\n PRE-INSTALLATION COMPLETE. You must run 'sudo dpkg -i {{DOWN}}/{{OSCAR_PACKAGE}}' to install oscar!"
    when: OSCAR_DEB_VERSION|int < 694
